### ISSUE TITLE
Span type buttons all get highlighted when you use only one

### ISSUE THREAD

**Issue by twd3** [jacksleight/statamic-bard-texstyle#1]
## Bug Description
For the span type if I have multiple span types and I use one, all span type buttons get highlighted and not just the one I'm using.

## How to Reproduce
Make three span types. Go to CP and use just one. They will all be highlighted and not just the one you used.

## Extra Detail
https://user-images.githubusercontent.com/16004958/144484626-d5e4f66b-1e87-4514-8fbd-f4b8975dd5dd.mp4

## Environment
Statamic 3.2.24 Pro
Laravel 8.74.0
PHP 8.0.10
aryehraber/statamic-captcha 1.7.0
doublethreedigital/duplicator 2.0.1
jacksleight/statamic-bard-mutator 1.0.1
jacksleight/statamic-bard-texstyle dev-main
spatie/statamic-responsive-images 2.8.5

**Comment by jacksleight** [comment]
Well spotted, I hadn’t tested multiple spans. Looks like this is actually due to a bug in TipTap, but there’s a workaround.

**Comment by twd3** [comment]
You. Are. The. Man! Thank you for this awesome addon!
