### ISSUE TITLE
Support multiple default classes

### ISSUE THREAD

**Issue by aerni** [jacksleight/statamic-bard-texstyle#14]
I really love the ability to set default classes to elements that have no style set. However, in practice, I'm finding the implementation a bit limiting, making me jump back and forth between this addon and [Statamic Classify](https://github.com/visuellverstehen/statamic-classify). 

The problem I'm having with the current implementation is that it only allows for one set of default styles. In my projects, I've got lots of different Bard fields like article, accordion, and various description fields. And each field needs different styling.

It would be lovely if we could set default classes that apply for all Bard fields and additionally add classes that only apply for certain Bard fields. Similar to how Statamic Classify handles this situation. It lets you configure multiple arrays of classes and then apply them in the view using a modifier like `{{ text | classify:article }}`. I'm not quite sure how you would solve this issue in Bard Texstyle. You might be able to make it smart and get the appropriate classes by array key or something.

Here's an example configuration of Statamic Classify in a current project:

```php
'article' => [
    'h2' => 'font-bold text-lg leading-relaxed mt-10 first:mt-0',
    'p' => 'text-lg leading-[1.75] my-8 first:mt-0 last:mb-0',
    'a' => 'font-medium border-b-2 border-black hover:motion-safe:transition hover:text-gray-500 hover:border-gray-500 focus:outline-none focus-visible:rounded focus-visible:pt-1 focus-visible:pb-0.5 focus-visible:mb-0.5 focus-visible:bg-brand-yellow focus-visible:border-transparent focus-visible:ring-2 focus-visible:ring-black',
    'ul' => 'text-base leading-relaxed 2xl:text-lg 2xl:leading-relaxed my-6 first:mt-0 last:mb-0 border-l-4 border-brand-yellow list-disc pl-8 space-y-1',
    'ol' => 'text-base leading-relaxed 2xl:text-lg 2xl:leading-relaxed my-6 first:mt-0 last:mb-0 border-l-4 border-brand-yellow list-decimal marker:font-bold pl-8 space-y-1',
    'li' => 'text-base leading-relaxed 2xl:text-lg 2xl:leading-relaxed pl-1',
    'ul li p' => 'my-0',
    'ol li p' => 'my-0',
],

'course_description' => [
    'p' => 'text-base leading-relaxed my-4 2xl:text-lg 2xl:leading-relaxed first:mt-0 last:mb-0',
    'a' => 'font-medium border-b-2 border-black hover:motion-safe:transition hover:text-gray-500 hover:border-gray-500 focus:outline-none focus-visible:rounded focus-visible:pt-1 focus-visible:pb-0.5 focus-visible:mb-0.5 focus-visible:bg-brand-yellow focus-visible:border-transparent focus-visible:ring-2 focus-visible:ring-black',
    'ul' => 'text-base leading-relaxed 2xl:text-lg 2xl:leading-relaxed my-6 first:mt-0 last:mb-0 border-l-4 border-brand-yellow list-disc pl-8 space-y-1',
    'ol' => 'text-base leading-relaxed 2xl:text-lg 2xl:leading-relaxed my-6 first:mt-0 last:mb-0 border-l-4 border-brand-yellow list-decimal marker:font-bold pl-8 space-y-1',
    'li' => 'text-base leading-relaxed 2xl:text-lg 2xl:leading-relaxed pl-1',
    'ul li p' => 'my-0',
    'ol li p' => 'my-0',
],

'accordion' => [
    'h4' => 'font-bold text-lg leading-relaxed mt-10 first:mt-0',
    'h4 a' => 'border-b-2 border-black hover:motion-safe:transition hover:text-gray-500 hover:border-gray-500 focus:outline-none focus-visible:rounded focus-visible:pt-1 focus-visible:pb-0.5 focus-visible:mb-0.5 focus-visible:bg-brand-yellow focus-visible:border-transparent focus-visible:ring-2 focus-visible:ring-black',
    'p' => 'text-base leading-relaxed my-4 first:mt-0 last:mb-0',
    'a' => 'font-medium border-b-2 border-black hover:motion-safe:transition hover:text-gray-500 hover:border-gray-500 focus:outline-none focus-visible:rounded focus-visible:pt-1 focus-visible:pb-0.5 focus-visible:mb-0.5 focus-visible:bg-brand-yellow focus-visible:border-transparent focus-visible:ring-2 focus-visible:ring-black',
    'ul' => 'text-base leading-relaxed my-6 first:mt-0 last:mb-0 border-l-4 border-brand-yellow list-disc pl-8 space-y-1',
    'ol' => 'text-base leading-relaxed my-6 first:mt-0 last:mb-0 border-l-4 border-brand-yellow list-decimal marker:font-bold pl-8 space-y-1',
    'li' => 'text-base leading-relaxed pl-1',
    'ul li p' => 'my-0',
    'ol li p' => 'my-0',
],
```

The problem I'm facing right now is that I need custom Bard buttons – which is why I'm using this addon – and additionally need to apply classes to default elements. I've tried mix and matching Bard Texstyle and Statamic Classify. But Statamic Classify is pretty aggressive and just strips out any class that was applied by Bard Texstyle.

What do you think? Have you ever come across this situation before? It seems like it's a pretty common issue. It's hard to believe that I'm the only one needing different styling for different Bard fields 😅

**Comment by jacksleight** [comment]
It’s not really something I’ve run into myself, I tend to put those kind of styles in CSS with a single wrapper class, but I can see how it could be useful.

Texstyle does its thing during the ProseMirror rendering process, but at the moment it’s very tricky to get additional contextual values (such as the name of the class set you want to use) into those methods. I have plans for a Statamic PR that would make this possible, but it’d have to be a 3.4 / Texstyle 2 feature. The selection of the class set would be implemented as a field config option, would that still work for your use case?

**Comment by aerni** [comment]
Yes, this sounds perfect!

**Comment by jacksleight** [comment]
@aerni I have this working now, if you wanted to give it a try: https://github.com/jacksleight/statamic-bard-texstyle/pull/16. You'd need to install the master branch of Statamic though. Will release it in 2.0, which will be out as soon as Statamic 3.4 is.

**Comment by aerni** [comment]
@jacksleight Thanks! I don't have the capacity to test this right now. I will hopefully get to it at some point.

**Comment by jacksleight** [comment]
Will be in 2.0
