### ISSUE TITLE
FR: custom icons

### ISSUE THREAD

**Issue by el-schneider** [jacksleight/statamic-bard-texstyle#15]
Hey Jack,

thanks again for this awesome plugin! 

Lately I felt quite often, that it would be really nice to be able to choose an svg icon instead of the idents, as the put a lot of emphasis on the underlying html-element which is not always of great importance to the end-user and can be rather cryptic as a result.

For example I have simple style for a brand color red of a client, that looks like this: 
<img width="237" alt="grafik" src="https://user-images.githubusercontent.com/26460248/183688994-58e3a7d8-290e-43b6-916b-9be0153322b3.png">

Instead it would be nice if this could just be red dot (or something like that).
<img width="237" alt="grafik" src="https://user-images.githubusercontent.com/26460248/183690404-9c2b7a38-15e1-4798-9d28-9f0742505f3c.png">

Likewise being able to chose an icon could be used to set-up text-alignment and probably a lot more.

What do you think?

**Comment by jacksleight** [comment]
> What do you think?

I think it's a great idea, and it's already in the bag for 2.0 😊 . Take a look at the `icon` option in https://github.com/jacksleight/statamic-bard-texstyle/blob/bard2/README.md#configuration

There are a handful of pre-defined icons that use the ident, or you can specify custom html (like an svg). Here's a quick preview:

![Screenshot 2022-08-09 at 17 03 32](https://user-images.githubusercontent.com/126740/183701840-25a82404-fad9-4090-a67c-4779352fafe4.png)

2.0 will work with the new Bard 2 in Statamic 3.4 and will be released as soon as that is.

FYI: Hopefully Statamic 3.4 will have built-in text align support as well.

**Comment by el-schneider** [comment]
Nice! Let's hope 3.4 is coming soon

**Comment by el-schneider** [comment]
I know, I'm pretty sure I was the first user outside the team. 😎 Great work as always!
