### ISSUE TITLE
Running old versions or free edition prompts you to buy a license

### ISSUE THREAD

**Issue by lchristodoulou-tickmill** [jacksleight/statamic-bard-texstyle#28]
## Bug Description
From the time v2 of the plugin released when running 1.0.3 edition, statamic prompt you that you need to buy a license, when you buy the license you cannot switch to pro version and throws an exception since 1.0.3 doesn't have a pro version. I currently cannot update to statamic v3.4  since some breaking changes has to be resolved first in order to update to the latest version. If its possible please add license support for v1 of the plugin so it will stop prompt you for a license.

## Extra Detail
![image](https://user-images.githubusercontent.com/124154838/218474259-a3bf3768-a749-4586-a587-a919c687b45b.png)
![image](https://user-images.githubusercontent.com/124154838/218474590-a2053460-f5d6-44b5-8936-1074692ed338.png)
![image](https://user-images.githubusercontent.com/124154838/218474931-c3d9662b-ea32-4ef6-8936-e4d42790d61d.png)

## Environment
Application Name: Tickmill
Laravel Version: 9.48.0
PHP Version: 8.1.8
Composer Version: 2.2.4
Environment: local
Debug Mode: ENABLED
URL: tickmill.com.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single, bugsnag, elasticsearch
Mail: smtp
Session: file

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 3.3.65 PRO

Statamic Addons
edalzell/forma: 1.2
jacksleight/statamic-bard-mutator: 1.1.3
jacksleight/statamic-bard-texstyle: 1.0.3
simonhamp/gitamic: 1.8.4

**Comment by jacksleight** [comment]
Hey. I'm aware of this and Statamic support are currently looking into it. Existing users of the free edition shouldn't be affected by the new Pro edition at all and don't need to buy a licence.

I will update as soon as I hear back. Sorry for any inconvenience. 🙁

**Comment by jacksleight** [comment]
The unlicensed addon error should now be fixed for anyone on versions prior to 2.1.

There's still an outstanding issue with the free edition of 2.1.

Thanks for your patience.

**Comment by leonidastickmill23** [comment]
Thanks !!

**Comment by jacksleight** [comment]
All sorted 👍
