### ISSUE TITLE
Add ability to customize default elements

### ISSUE THREAD

**Issue by aerni** [jacksleight/statamic-bard-texstyle#3]
Thanks for this great addon! Now I can finally add custom span elements. Awesome!

One thing I'm missing is the ability to add classes for default elements like H1, Paragraph, Lists, etc. I saw that you can add classes using [Statamic Bard Mutator](https://github.com/jacksleight/statamic-bard-mutator). However, this is quite inconvenient and could probably be abstracted to a config file. I'm thinking of something similar to how [Statamic Classify](https://github.com/visuellverstehen/statamic-classify) does it.

Adding this feature would give us full control over Bard styles.

**Comment by aerni** [comment]
Also, one important drawback of this addon compared to [Statamic Classify](https://github.com/visuellverstehen/statamic-classify) is that it saves the classes to the content. If you later decide to change some classes you have to go in and change all the content files. It would probably be better if the classes were never saved to the content and just added on runtime. This is already the case if you use the [Statamic Bard Mutator](https://github.com/jacksleight/statamic-bard-mutator) in a Service Provider.

You probably have a reason to save the classes to the content that I don't know of. Just sharing my thoughts here.

**Comment by jacksleight** [comment]
I like this idea, I'm just thinking it might be better as part of Bard Mutator, which is a dependency of Texstyle anyway.

As you mention this is already possible with Mutator, but you do have to write all of your own mutator functions which is a bit of a chore when they only need to be very simple. Perhaps I could add some kind of automatic mode to Mutator that will do certain mutations for you based on a config file, similar to Classify.

I'm hesitant to add such a feature to this addon as Texstyle only deals with headings, paragraphs and spans, and only class attributes. If this could add defaults to node types beyond that set (eg. lists) it could cause confusion. It would also make sense to extend the functionality beyond just classes. eg. setting default `rel` attributes.

What do you think?

> Also, one important drawback of this addon compared to Statamic Classify is that it saves the classes to the content. If you later decide to change some classes you have to go in and change all the content files. It would probably be better if the classes were never saved to the content and just added on runtime. 

The reason for that is that Textstyle allows you to toggle between multiple different heading, paragraph or span classes, or not use them at all. It has to save them to the content so it knows which one was selected. Mutator on the other hand can only do blanket "give every X a class of Y" rules.

**Comment by jacksleight** [comment]
> I agree that it probably makes sense to add it as part of Bard Mutator. Though it would be convenient to have the same addon to similar things from a user perspective.

I'll definitely add that to Mutator, I think it would be very useful for simple use cases. I agree it would be nice to do all the class stuff in one place... I'm just a bit wary of blurring the lines when it comes to what this addon is for/can do. The options I can see are:

1. No ability to set default classes in Texstyle, do it in Mutator
    * Pro: Keeps current functionality clearly separated
    * Con: You have to manage default classes and toggle-able classes in two separate config files
2. Limited ability to set heading, paragraph and span classes in Texstyle, do anything else in Mutator
    * Pro: You can manage all your heading, paragraph and span classes in one place
    * Con: You still have to manage other node's default classes in a different config file
3. Full ability to set any node's default classes in Texstyle
    * Pro: It's all in one place
    * Con: You'd be able to alter nodes that Texstyle doesn't support normally, which could be confusing

I will give it some thought. 🙂

> As for the classes being saved to content; Maybe we can not save the actual classes to the content but only an identifier. Then pick up on this identifier and add the classes later.

Ah yeah, this did come up when I was developing it, I actually went round in a circle on it. The main reason it saves the classes currently is that I wanted to keep the content as generic and flexible as possible, eg. if someone had other addons/code that could manipulate classes the two could work together, if Texstyle used it's own internal identifiers that wouldn't be possible. (I also had to maintain BC with [Bard Paragraph Style](https://github.com/jacksleight/bard-paragraph-style)).

However, I can totally see the argument for independent identifiers, so classes can be altered without having to update content. I could add this as a configurable option fairly easily, so if you wanted to use that mode you could switch it on.

**Comment by aerni** [comment]
Awesome! Let me know if I can help with anything.

> However, I can totally see the argument for independent identifiers, so classes can be altered without having to update content. I could add this as a configurable option fairly easily, so if you wanted to use that mode you could switch it on.

This would be great!

**Comment by jacksleight** [comment]
I've started on the identifier storage feature: https://github.com/jacksleight/statamic-bard-texstyle/pull/5

If you felt like giving it a test and had any thoughts on the implementation feedback is always very welcome!

**Comment by jacksleight** [comment]
Sorry it's taken me so long to look at this. I couldn't decide how or where it should be done, but I think implementing it in Texstyle is fine.

PR is currently draft, just have some bits to tidy up and docs to add, will get this released next week.
