### ISSUE TITLE
Styles type "link" doesn't work

### ISSUE THREAD

**Issue by richarderoche** [jacksleight/statamic-bard-texstyle#35]
## Bug Description
In the styles config, when using: `'type' => 'link'` nothing shows up in the bard toolbar.

## How to Reproduce
Uncomment the 'action' block in the default config, create a bard field with the 'action' button enabled. Go to CP and see no button.

## Environment
Laravel Version: 9.52.0
PHP Version: 8.1.12
Composer Version: 2.2.3

Statamic
Version: 3.4.5 PRO

jacksleight/statamic-bard-texstyle: 2.1.1

**Comment by jacksleight** [comment]
I've added this to the docs now: https://jacksleight.dev/docs/bard-texstyle/getting-started#link-style-buttons

Thanks for reporting!
