### ISSUE TITLE
Missing styles dropdown?

### ISSUE THREAD

**Issue by wturrell** [jacksleight/statamic-bard-texstyle#41]
I'm slightly confused - struggling to find how to get the styles dropdown shown in the Marketplace screenshot (below) - assuming the design of the Addon is still current:

![](https://statamic.com/storage/products/JREEcdWwnbrCPPnprai34R9bs5b5bdRN8cfUspOG.png)

When editing the Bard field in a blueprint, I can enable buttons for the uncommented individual styles from bard_tex (title, lead etc.), and correctly apply those styles to an entry, but there's no 'Aa' button icon and no dropdown anywhere?

(Statamic 3.4.7, standard mode, and Pro not enabled for Textile)

Thanks!

**Comment by jacksleight** [comment]
Hey. The styles menu is [part of Pro](https://jacksleight.dev/docs/bard-texstyle), so you'll need to enable that.

**Comment by wturrell** [comment]
Ah, got it - thanks.
