### ISSUE TITLE
Empty Style/Attributes Dropdown

### ISSUE THREAD

**Issue by janoschdigg** [jacksleight/statamic-bard-texstyle#48]
## Bug Description
**Attributes Dropdown is empty**
<img width="309" alt="image" src="https://github.com/jacksleight/statamic-bard-texstyle/assets/26810953/a7110cf8-88df-48af-8d12-84b085e0e75b">
**Styles Dropdown is empty**
<img width="230" alt="image" src="https://github.com/jacksleight/statamic-bard-texstyle/assets/26810953/4254de71-54c0-41a9-bc39-b6f05d69a6df">

## How to Reproduce

1. Install the plugin via Composer
2. Enable Pro Mode
3. In bard_textstyle.php add all attributes and styles from comments

## Environment
```
Environment
Application Name: Statamic
Laravel Version: 10.10.1
PHP Version: 8.2.5
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: testplugin.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.1 Solo

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.0.2
```

**Comment by jacksleight** [comment]
Have you added options to the Styles dropdown? See https://jacksleight.dev/docs/bard-texstyle/styles#style-selection-menu-pro

When you're opening the attributes panel do you have an element you've added attributes for selected in the editor?

**Comment by jacksleight** [comment]
And are those options also enabled in the buttons bar? They have to be in there as well so that Statamic enables the relevant extensions. Can you share the field config?

**Comment by janoschdigg** [comment]
im Sorry you were right sorry for bothering

**Comment by jacksleight** [comment]
No problem, glad it's working now. 🙂
