### ISSUE TITLE
Addon not showing in CP under installed addons after update

### ISSUE THREAD

**Issue by twd3** [jacksleight/statamic-bard-texstyle#50]
Addon not showing in CP under installed addons after update even though I know it's installed.

## Environment
Environment
Application Name: Starter V4
Laravel Version: 10.11.0
PHP Version: 8.2.6
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: tdd-simp-v4.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: mailgun
Queue: sync
Session: file

Statamic
Addons: 6
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.1.2 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
aryehraber/statamic-logbook: 3.1.0
jacksleight/statamic-bard-mutator: 2.2.1
jacksleight/statamic-bard-texstyle: 3.1.0
ndx/statamic-bard-color-picker: 1.2.0
spatie/statamic-responsive-images: 4.0.2

**Comment by jacksleight** [comment]
Hey. Yup aware of this. Have asked support to look into it as it seems to be a core/marketplace issue as far as I can tell.

**Comment by jacksleight** [comment]
Related https://github.com/statamic/cms/issues/8166

**Comment by jacksleight** [comment]
Fixed in Statamic v4.19.0.
