### ISSUE TITLE
Can't undo link style

### ISSUE THREAD

**Issue by kobe-f8** [jacksleight/statamic-bard-texstyle#57]
https://github.com/jacksleight/statamic-bard-texstyle/assets/102222824/839bbdb2-1e8f-440c-9372-908a14797ce1

Video basically show my problem, I have a link that adds a custom style, but clicking the button again doesn't undo the styling

**Comment by kobe-f8** [comment]
I've figure out on a clean install that it has to do with changing the `store` setting to `key`

**Comment by jacksleight** [comment]
Thanks for the report, fixed in v3.1.4.
