### ISSUE TITLE
Clean up empty custom attribute keys

### ISSUE THREAD

**Issue by daun** [jacksleight/statamic-bard-texstyle#69]
When going through the git commit history after installing the addon, I'm seeing lots of empty TipTap attributes. Could this maybe be stripped out to avoid the noise in change logs and when editing the markdown directly?

<img width="866" alt="Screenshot 2024-07-01 at 18 28 22" src="https://github.com/jacksleight/statamic-bard-texstyle/assets/22225348/872e77de-6e02-4b1b-ad75-1ba0f3cad5ab">

**Comment by jacksleight** [comment]
Ignore my last comment, seems I was mis-remembering.

I'm not actually sure if this is possible, Tiptap always seems to save the blank attributes, you can see it's doing the same thing with the built-in `colwidth` attribute on the `tableCell` node. Defaulting it to `undefined` half works, but you still end up with an empty `attrs` list.

I will investigate a bit more, but this may not be something I can control.

**Comment by daun** [comment]
Thanks for investigating! If this is the default TipTap behavior, it might be better handled on the Statamic side of things anyway. I'll poke around a bit as well :)

**Comment by jacksleight** [comment]
From the ProseMirror/Tiptap developers:

> Attributes defined for a given node always have a value. It seems unproductive to worry about the JSON representation of such a node.

So that's a no I'm afraid.

**Comment by daun** [comment]
They do have a point, assuming json output is never seen or touched by humans — which with a flat-file cms doesn't hold true necessarily. I'll try to forget about this, and if this continues to bother me, I'll consider looking under the hood of Statamic. Thanks!
