### ISSUE TITLE
Using Antlers Dump Tag in the Antlers Pin file is returning 6 duplications of data for each Pin used on page

### ISSUE THREAD

**Issue by fixr-austin** [jacksleight/statamic-bard-texstyle#77]
## Bug Description
Using Antlers {{dump}} tag in the Antlers Pin file is returning 6 duplications of data for each Pin used on page

## How to Reproduce
I added a Pin to my Bard content inside of one of my collection entries. 

Inside `bard_texstyle.php` my pins are set to:
```
'pins' => [

        'state_data' => [
            'display' => 'Location Data',
            'icon' => 'puzzle-piece',
            'fields' => [
                'state_selected' => [
                    'display' => 'Select State',
                    'type' => 'select',
                    'options' => [
                        'slug' => 'Based on Slug',
                        'alabama' => 'Alabama',
                        'alaska' => 'Alaska',
                        'arizona' => 'Arizona',
                    ],
                    'default' => 'slug',
                ],
                'data_type' => [
                    'display' => 'Data Type',
                    'type' => 'select',
                    'options' => [
                        'title' => 'State Name',
                        'slug' => 'State Slug',
                        'image' => 'State Image',
                        'demonym' => 'State Demonym',
                        'city_name' => 'City Name',
                    ],
                    'default' => 'title',
                    'preview' => true,
                ],
                'prepended_text' => [
                    'display' => 'Prepend Text',
                    'type' => 'text',
                    'preview' => true,
                ],
                'appended_text' => [
                    'display' => 'Append Text',
                    'type' => 'text',
                    'preview' => true,
                ],
            ],
        ],
```

Then, inside my `pins/_state_data.antlers.html`, I am using the Antlers tag `{{dump:state_selected}}` to see what data would come up, but it returns 6 duplicate data results for just the 1 pin.

## Extra Detail

Here's the Pin being used inside the Bard field:
<img width="432" alt="Screenshot 2024-10-29 at 6 20 47 PM" src="https://github.com/user-attachments/assets/e0a83b5d-c476-4536-9cb1-4a57288f5d26">

Here is the `pins/_state_data.antlers.html` file:
<img width="237" alt="Screenshot 2024-10-29 at 5 51 10 PM" src="https://github.com/user-attachments/assets/51f3da3f-fd59-49da-ae8d-f6d6811ca77b">

Here is the dump data being returned in the view:
<img width="608" alt="Screenshot 2024-10-29 at 6 18 44 PM" src="https://github.com/user-attachments/assets/83762849-8191-419d-8d6b-41d5ca53a548">

## Environment

Environment
Application Name: SR
Laravel Version: 11.26.0
PHP Version: 8.3.9
Composer Version: 2.7.7
Environment: local
Debug Mode: OFF
URL: localhost
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: pgsql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 3
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.35.0 PRO

Statamic Addons
jacksleight/statamic-bard-texstyle: 3.3.1
ndx/statamic-bard-color-picker: 2.0.0
statamic/eloquent-driver: 4.15.0

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: eloquent
Collection Trees: file
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file

**Comment by jacksleight** [comment]
Thanks for the report. This actually happens for two reasons:

1. The Tiptap library calls the render method twice. This is something I can detect and can skip the secondary call as it isn't needed for pins.
2. The Antlers parser [augments the bard value multiple times](https://github.com/statamic/cms/issues/5784). This isn't really something I can do anything about unfortunately.

The fix for the Tiptap call is released in v3.3.2.
