### ISSUE TITLE
Pins throw handle() on null error in config fields

### ISSUE THREAD

**Issue by mikemartin** [jacksleight/statamic-bard-texstyle#78]
## Bug Description
Hey @jacksleight 
It looks like the workaround you added for https://github.com/jacksleight/statamic-bard-texstyle/issues/74, doesn't work for config fields and throws an error.

`Call to a member function handle() on null`

This is what returns from `$this->options['bard'];`:
<img width="452" alt="Screenshot 2024-11-15 at 8 36 58 PM" src="https://github.com/user-attachments/assets/31224a52-2bc6-4e2b-80c3-3712d36a7089">

## How to Reproduce

- Add bard field as fieldtype config field
- Add and configure pins

**Comment by jacksleight** [comment]
Curious, that fix was related to frontend rendering not config fields. Did it work fine in 3.3.0?

Also, just out of interest what's the use case for using pins in a config field? In the CP they'd never be rendered anyway.

**Comment by mikemartin** [comment]
Thanks for the quick response. Yes, I've rolled back to 3.3 and it's working.

The use case is for forms rendered on the frontend, with a bard config field used for instructiuons / help text.

**Comment by jacksleight** [comment]
A gotcha. Will check it out. What does your pin template look like?

**Comment by jacksleight** [comment]
Fixed in v3.3.3
