### ISSUE TITLE
Ability to assign styles/classes to link elements

### ISSUE THREAD

**Issue by jacksleight** [jacksleight/statamic-bard-texstyle#9]
From a request on Discord

**Comment by jacksleight** [comment]
For now this isn't possible because the `updateMark` command in ProseMirror can't set a single attribute on a mark without losing the other attributes, which renders the links useless. You have the same problem when a link is updated through Statamic's link editor, where you lose the assigned class.

I will leave this open as I'd like to revisit it in future if a solution can be found.

**Comment by sjclark** [comment]
😉 would also be great if it could handle lists; tried:
```
        'ticklist' => [
            'type' => 'unorderedlist',
            'name' => 'Ticked List',
            'ident' => '✔️',
            'class' => 'ticked',
            'cp_css' => '',
        ],
```
But it wasn't to be 😄

**Comment by jacksleight** [comment]
Lists are actually planned for a future version (along with a couple of other things). Just waiting for Statamic 3.4 and the Tiptap 2 upgrade first.

**Comment by sjclark** [comment]
Sounds great 😊

**Comment by jacksleight** [comment]
@sjclark Links are now supported in v2.1: https://github.com/jacksleight/statamic-bard-texstyle/releases/tag/2.1.0
